# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

# Setup
title:               Amit Rajaraman
tagline:             
description:         The links below should lead to wherever you want to go, feel free to explore!
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            1

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0

# Fill in your Google Analytics gtag.js ID to track your website using gtag
gtag: "UA-164224546-1"

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-164224546-1"

# Google Tag Manager ID
#gtm: ""

collections:
  notes:
    output: true